#!/bin/bash

# Do nothing if branch didn't change 
test "$3" = "1" || exit 0

function mklink() {
ln -sf hosts.$1 hosts && echo "Link: hosts -> hosts.$1" || echo "Failed to create link hosts -> hosts.$1";
}

current_branch=$(git rev-parse --abbrev-ref HEAD)
if [[ "$current_branch" = "prod" || "$current_branch" = *".prod" ]]; then
        mklink prod
else
        mklink test
fi
